version: '2'
services:
  mysql:
    image: mysql:5.7.17
    ports:
      - "3306:3306"
    volumes:
      - ./mysql-data:/var/lib/mysql
      - /etc/localtime:/etc/localtime:ro
    environment:
      - MYSQL_ROOT_PASSWORD=ops-warehouse_*()123
      - MYSQL_DATABASE=INMDS
      - MYSQL_USER=inm
      - MYSQL_PASSWORD=In_*()123
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci

  rabbitmq:
    image: rabbitmq:3-management
    restart: always
    ports:
      - 15672:15672
    volumes:
      - /etc/localtime:/etc/localtime:ro
    logging:
      options:
        max-size: "10m"
        max-file: "10"
    depends_on:
      - mysql

  config-service:
    image: warehouse/config-service:1.0-SNAPSHOT-${BUILD_NUMBER}
    environment:
      - MICRO_SERVICE_PASSWORD=$MICRO_SERVICE_PASSWORD
      - SPRING_PROFILES_ACTIVE=native,docker
    restart: always
    logging:
      options:
        max-size: "10m"
        max-file: "10"
    depends_on:
      - rabbitmq
  registry-service:
    environment:
      - MICRO_SERVICE_PASSWORD=$MICRO_SERVICE_PASSWORD
      - SPRING_PROFILES_ACTIVE=docker
    image: warehouse/registry-service:1.0-SNAPSHOT-${BUILD_NUMBER}
    restart: always
    ports:
      - 8761:8761
    logging:
      options:
        max-size: "10m"
        max-file: "10"
    depends_on:
      - config-service

  auth-service:
    environment:
      - MICRO_SERVICE_PASSWORD=$MICRO_SERVICE_PASSWORD
      - SPRING_PROFILES_ACTIVE=docker
    image: warehouse/auth-service:1.0-SNAPSHOT-${BUILD_NUMBER}
    restart: always
    ports:
      - 5000:5000
    logging:
      options:
        max-size: "10m"
        max-file: "10"
    depends_on:
      - registry-service


  account-service:
    environment:
      - MICRO_SERVICE_PASSWORD=$MICRO_SERVICE_PASSWORD
      - SPRING_PROFILES_ACTIVE=swagger-ui,docker
    image: warehouse/account-service:1.0-SNAPSHOT-${BUILD_NUMBER}
    restart: always
    ports:
      - 6000:6000
    logging:
      options:
        max-size: "10m"
        max-file: "10"
    depends_on:
      - registry-service

  edge-service:
    environment:
      - MICRO_SERVICE_PASSWORD=$MICRO_SERVICE_PASSWORD
      - SPRING_PROFILES_ACTIVE=swagger-ui,docker
    image: warehouse/edge-service:1.0-SNAPSHOT-${BUILD_NUMBER}
    restart: always
    ports:
      - 4000:4000
    logging:
      options:
        max-size: "10m"
        max-file: "10"
    depends_on:
      - registry-service


  warehouse-service:
    environment:
      - MICRO_SERVICE_PASSWORD=$MICRO_SERVICE_PASSWORD
      - SPRING_PROFILES_ACTIVE=swagger-ui,docker
    image: warehouse/warehouse-service:1.0-SNAPSHOT-${BUILD_NUMBER}
    restart: always
    ports:
      - 7000:7000
    logging:
      options:
        max-size: "10m"
        max-file: "10"
    depends_on:
      - registry-service

  monitor-dashboard:
    environment:
      - MICRO_SERVICE_PASSWORD=$MICRO_SERVICE_PASSWORD
      - SPRING_PROFILES_ACTIVE=docker
    image: warehouse/monitor-dashboard:1.0-SNAPSHOT-${BUILD_NUMBER}
    restart: always
    ports:
      - 8080:8080
    logging:
      options:
        max-size: "10m"
        max-file: "10"
    depends_on:
      - registry-service
