server:
  port: 4000

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 20000

ribbon:
  ReadTimeout: 20000
  ConnectTimeout: 20000

---
spring:
  profiles: dev
datasource:
    url: jdbc:mysql://localhost:3306/zxga_analyse?useSSL=false&useUnicode=true&characterEncoding=utf-8
    username: root
    password:
    testWhileIdle: true
    validationQuery: select 1


zuul:
  ignoredServices: '*'
  host:
    connect-timeout-millis: 20000
    socket-timeout-millis: 20000

  routes:
    auth-service:
      path: /uaa/**
      url: http://localhost:5000
      stripPrefix: false
      sensitiveHeaders: Cookie,Set-Cookie

    account-service:
      path: /accounts/**
      serviceId: account-service
      stripPrefix: false
      sensitiveHeaders: Cookie,Set-Cookie

    warehouse-service:
      path: /warehouses/**
      serviceId: warehouse-service
      stripPrefix: false
      sensitiveHeaders: Cookie,Set-Cookie
    analyse-service:
      path: /analyses/**
      serviceId: alalyse-service
      stripPrefix: false
      sensitiveHeaders: Cookie,Set-Cookie


---
spring:
  profiles: docker

zuul:
  ignoredServices: '*'
  host:
    connect-timeout-millis: 20000
    socket-timeout-millis: 20000

  routes:
    auth-service:
      path: /uaa/**
      url: http://auth-service:5000
      stripPrefix: false
      sensitiveHeaders: Cookie,Set-Cookie

    account-service:
      path: /accounts/**
      serviceId: account-service
      stripPrefix: false
      sensitiveHeaders: Cookie,Set-Cookie

    analyse-service:
      path: /analyses/**
      serviceId: analyse-service
      stripPrefix: false
      sensitiveHeaders: Cookie,Set-Cookie
