logging:
  level:
    org.springframework.security: DEBUG

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 20000


u4a:
  user:
    initialAdmin:
      username: admin
      password: 123456

---
spring:
  profiles: swagger-ui
swagger:
  enabled: true

---
spring:
  rabbitmq:
    host: localhost
  profiles: dev

micro-service-password: 123456

eureka:
  instance:
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

security:
  oauth2:
    resource:
      user-info-uri: http://localhost:5000/uaa/users/current

---
spring:
  profiles: docker
  rabbitmq:
    host: rabbitmq


micro-service-password: ${MICRO-SERVICE-PASSWORD}

eureka:
  instance:
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://registry-service:8761/eureka/

security:
  oauth2:
    resource:
      user-info-uri: http://auth-service:5000/uaa/users/current

